apiVersion: v1
kind: Service
metadata:
  labels:
    app: employee-mongodb
  name: employee-mongo-service
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    app: employee-mongodb